<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Overblikk.aspx.cs" Inherits="Timeregistreringssystem.Prosjektadmin.Overblikk" %>


<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">

        <asp:GridView ID="gridViewTeam" runat="server" OnSelectedIndexChanged="gridViewTeam_SelectedIndexChanged"
             AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" AutoGenerateColumns="False"
             BackColor="White" BorderColor="Black" BorderStyle="Solid" CellPadding="5" 
             OnRowEditing="gridViewTeam_RowEditing" OnRowDeleting="gridViewTeam_RowDeleting"
             DataKeyNames="ID" DataSourceID="SqlDataSource1" >

            <Columns>
                <asp:BoundField DataField="ID" HeaderText="ID" SortExpression="ID" ReadOnly="true" InsertVisible="False"/>
                <asp:BoundField DataField="Navn" HeaderText="Navn" SortExpression="Navn"/>
                <asp:BoundField DataField="Oppsummering" HeaderText="Oppsummering" SortExpression="Oppsummering"/>
                <asp:BoundField DataField="ansvarligID" HeaderText="ansvarligID" SortExpression="ansvarligID"/>
                <asp:BoundField DataField="Neste_Fase" HeaderText="Neste_Fase" SortExpression="Neste_Fase" />
                <asp:BoundField DataField="Neste_Milepæl" HeaderText="Neste_Milepæl" SortExpression="Neste_Milepæl"/>
            </Columns>

         <HeaderStyle BackColor="#CCCCFF" ForeColor="Black" />
         <selectedrowstyle backcolor="White" forecolor="Black"
         font-bold="True" BorderColor="Black"/> 
        </asp:GridView>

        <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
            ConnectionString="<%$ ConnectionStrings:HLVDKN_DB1ConnectionString %>" 
            ProviderName="<%$ ConnectionStrings:HLVDKN_DB1ConnectionString.ProviderName %>" 
            DeleteCommand="DELETE FROM Prosjekt WHERE ID = @ID"
            SelectCommand="SELECT Prosjekt.* FROM Prosjekt"
            UpdateCommand="UPDATE Prosjekt SET  Navn =@Navn,  Oppsummering = @Oppsummering, ansvarligID =@ansvarligID, `Neste_Milepæl` = @`Neste_Milepæl`, Neste_Fase = @Neste_Fase"
            >
        <DeleteParameters>
            <asp:Parameter Name="ID" Type="Int32" />
        </DeleteParameters>
        <UpdateParameters>
            <asp:Parameter Name="ID" Type="Int32" />
            <asp:Parameter Name="Beskrivelse" Type="String" />
            <asp:Parameter Name="Teamleder" Type="Int32" />
        </UpdateParameters>
        </asp:SqlDataSource>
    
    </asp:Content>
