<%@ Page Title="Brukeradministrasjon" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="EndreBruker.aspx.cs" Inherits="Timeregistreringssystem.BrukerAdministrasjon.EndreBruker" %>

<asp:Content ID="EndreBrukerContent" ContentPlaceHolderID="MainContent" runat="server">

    <h1><%: Title %></h1>

    <asp:GridView ID="gwEndreBruker" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" DataKeyNames="ID" DataSourceID="EndreBrukerDataSource" AutoGenerateEditButton="True">
        <Columns> 
            <asp:BoundField DataField="ID" HeaderText="ID" InsertVisible="False" ReadOnly="True" SortExpression="ID" />
            <asp:BoundField DataField="Brukernavn" HeaderText="Brukernavn" SortExpression="Brukernavn" />
            <asp:BoundField DataField="Fornavn" HeaderText="Fornavn" SortExpression="Fornavn" />
            <asp:BoundField DataField="Mellomnavn" HeaderText="Mellomnavn" SortExpression="Mellomnavn" />
            <asp:BoundField DataField="Etternavn" HeaderText="Etternavn" SortExpression="Etternavn" />
            <asp:BoundField DataField="Epost" HeaderText="Epost" SortExpression="Epost" />
            <asp:BoundField DataField="IM" HeaderText="IM" SortExpression="IM" />
            <asp:BoundField DataField="Telefonnr" HeaderText="Telefonnr" SortExpression="Telefonnr" />
            <asp:BoundField DataField="Adresse" HeaderText="Adresse" SortExpression="Adresse" />
            <asp:BoundField DataField="Postnummer" HeaderText="Postnummer" SortExpression="Postnummer" />
            <asp:BoundField DataField="By" HeaderText="By" SortExpression="By" />
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="EndreBrukerDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:HLVDKN_DB1ConnectionString %>" ProviderName="<%$ ConnectionStrings:HLVDKN_DB1ConnectionString.ProviderName %>"
        SelectCommand="SELECT ID, Brukernavn, Fornavn, Mellomnavn, Etternavn, Epost, IM, Telefonnr, Adresse, Postnummer, `By` FROM Bruker" 
        UpdateCommand="UPDATE Bruker SET Brukernavn = @Brukernavn, Fornavn = @Fornavn, Mellomnavn = @Mellomnavn, Etternavn = @Etternavn, Epost = @Epost, IM = @IM, Telefonnr = @Telefonnr, Adresse = @Adresse, Postnummer = @Postnummer, `By` = @By WHERE ID = @ID"
        DeleteCommand="Delete FROM Bruker Where ID = @ID"
        >

    </asp:SqlDataSource>

    <br />





</asp:Content>
